# Generated by Django 5.0.1 on 2024-02-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('image', models.ImageField(default='default_hospital.jpg', upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='default_doctor.jpg', upload_to='images'),
        ),
    ]
