# Generated by Django 5.0.1 on 2024-02-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
