# Generated by Django 5.0.1 on 2024-02-08 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_remove_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 11, 27, 30, 195688, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
