# Generated by Django 5.0.1 on 2024-02-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_remove_medicalcondition_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consent_to_store_history',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_diagnosed', models.DateField()),
                ('treatment', models.TextField()),
                ('outcome', models.CharField(max_length=100)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicalcondition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
