# Generated by Django 5.0.1 on 2024-01-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.TextField(max_length=100)),
                ('phone', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('specialization', models.ManyToManyField(to='pages.specialization')),
            ],
        ),
    ]
